### ISSUE TITLE
[!] Unable to find a specification for `FINNBottomSheet`

### ISSUE THREAD

**Issue by summonerriftofficial** [finn-no/BottomSheet#25]
[!] Unable to find a specification for `FINNBottomSheet`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by blurtime** [comment]
I am getting the same error when trying `pod install`. Installing other pods works well, though, so I would assume the problem isn't on my side.

**Comment by MaidarD** [comment]
Try it.
pod 'FINNBottomSheet', :git => 'https://github.com/finn-no/bottom-sheet-ios.git'
Minimum target iOS 11.2.
