### ISSUE TITLE
Bottom sheet jumps to top when dismiss.

### ISSUE THREAD

**Issue by amadeu01** [finn-no/BottomSheet#30]
I basically, only copied the code from the readme

```
private func showSheet() {
        guard let parentVC = self.parentViewController else {
            return
        }
        let transitioningDelegate = BottomSheetTransitioningDelegate(
            contentHeights: [290, 300],
            startTargetIndex: 0,
            presentationDelegate: self
        )
        let viewController = UIViewController()
        viewController.transitioningDelegate = transitioningDelegate
        viewController.modalPresentationStyle = .custom

        parentVC.present(viewController, animated: true)
    }
```

and used the delegate like 

```
extension MyView: BottomSheetPresentationControllerDelegate {
    func bottomSheetPresentationController(
        _ controller: UIPresentationController,
        shouldDismissBy action: BottomSheetView.DismissAction
    ) -> Bool {
        return true
    }

    func bottomSheetPresentationController(
        _ controller: UIPresentationController,
        didCancelDismissBy action: BottomSheetView.DismissAction
    ) {

    }

    func bottomSheetPresentationController(
        _ controller: UIPresentationController,
        willDismissBy action: BottomSheetView.DismissAction?
    ) {
    }

    func bottomSheetPresentationController(
        _ controller: UIPresentationController,
        didDismissBy action: BottomSheetView.DismissAction?
    ) {}
}
```

I'm not sure why it jumps to the top of the parent view controller before dissmiss.

![bottomSheet](https://user-images.githubusercontent.com/11631092/93830904-e39fce00-fc47-11ea-97fd-957e4c0f4c27.gif)

**Comment by amadeu01** [comment]
I'm not sure why, but I think it is related to the reference of the `transitioningDelegate`. If we do not have a strong reference being kept by someone, and it gets lost. then, the dismiss will have this strange behaviour.

**Comment by aleks100s** [comment]
> I'm not sure why, but I think it is related to the reference of the `transitioningDelegate`. If we do not have a strong reference being kept by someone, and it gets lost. then, the dismiss will have this strange behaviour.

Yeah, thanks, that's a good advice

**Comment by fespinoza** [comment]
Indeed, it's about the strong reference to the transition delegate.

We should add some explanation to the README regarding that detail
