### ISSUE TITLE
Module name defined for Cocoapods is different than SwiftPM

### ISSUE THREAD

**Issue by fespinoza** [finn-no/BottomSheet#32]
When we import this module through cocoapods, we import

```
import FINNBottomSheet
```

when we do it through SPM we do

```
import BottomSheet
```

Then we need to fix this in order to support packages that offer cocoapods and spm integration.

What should be the exported module name?

ping @vadymmarkov

**Comment by fespinoza** [comment]
this will mean that we need to fix some imports after doing any change in here, I assume you use `import BottomSheet` @vadymmarkov

**Comment by vadymmarkov** [comment]
@fespinoza I'm still using this module through cocoapods, so if we have a convention to add FINN prefix for SPM I'm ok with it.
