### ISSUE TITLE
Multiple view controllers

### ISSUE THREAD

**Issue by fenixsolorzano** [finn-no/BottomSheet#34]
Is it possible to have multiple view controllers at different vertical positions?

**Comment by fespinoza** [comment]
I'm not entirely sure what you are asking, but if it's about presenting multiple bottom sheet at a time at different positions, we have not tried it.

But our main use case for this library is always to present **one** bottom sheet at a time, so this would be out of the scope of what this library is trying to do.

**Comment by shredlocker** [comment]
I guess you could add child view controllers to your view controller with the bottom sheet transitioning delegate and then organise the layout of the child views in any position within the bottom sheet.
