### ISSUE TITLE
Not implemented

### ISSUE THREAD

**Issue by dathu7728** [finn-no/BottomSheet#38]
getting error here

public required init?(coder: NSCoder) {
        fatalError("Not implemented")
    }

How to resolve this one ? @henrik242 @stigkj @oyvindio @sveisvei @ivarconr

**Comment by osanoj** [comment]
Not sure why you want to store the class to NSCoder and then load it from there? It is not something we use ourselves so there are no plans to implement that method, you will find the same throughout all our open source iOS code. 

If you need it you can always submit a PR.
