### ISSUE TITLE
SPM Cannot read manifest file

### ISSUE THREAD

**Issue by pr0tonion** [finn-no/BottomSheet#42]
Hi

Tried using Swift Package manager to try the sheet.

Seems like the manifest file cannot be parsed.

Swift version: 5.2.4

```
'init(name:defaultLocalization:platforms:pkgConfig:providers:products:dependencies:targets:swiftLanguageVersions:cLanguageStandard:cxxLanguageStandard:)' is unavailable

```

![Skjermbilde 2021-01-30 kl  14 58 46](https://user-images.githubusercontent.com/10840203/106358294-ae00a500-630b-11eb-8264-8d0939800ffa.png)

**Comment by hakloev** [comment]
Hi,

Thanks for letting us know. I've identified the issue and been able to reproduce it. Just made a PR, #43, that should solve the issue :)

**Comment by pr0tonion** [comment]
Thank you! That was almost too quick!😁 have a great week
